services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_KEY: base64:E3pVieBdirU9AuYHf02isGGtjvkPZgcaRxrv2yp0nS4=
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      VITE_API_URL: http://localhost:8090
    volumes:
      - ./database:/app/database
    depends_on:
      - python-api

  python-api:
    build:
      context: .
      dockerfile: python-api/Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./data:/data
      - ./python-api:/app
