services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./database:/app/database
    depends_on:
      - python-api

  python-api:
    build:
      context: .
      dockerfile: python-api/Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./data:/data
      - ./python-api:/app
